### Create passenger
POST http://localhost:9002/passengers/1/3


### Delete passenger
DELETE http://localhost:9002/passengers/1/3

### Update passenger
PUT http://localhost:9002/passengers/1/3
Content-Type: application/json

{
  "etat": "ACCEPTED"
}
