### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "jerome.strebelle@vinci.be",
  "firstname": "Catherine",
  "lastname": "Mireault",
  "password": "notsaying"
}

### Connect user
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "jerome.strebelle@vinci.be",
  "password": "notsaying"
}

> {% client.global.set("token", response.body) %}

### Read user by email
GET http://localhost:8080/users?email=jerome1.strebelle@vinci.be

### Update credentials
PUT http://localhost:8080/users
Authorization: {{token}}
Content-Type: application/json

{
  "email": "sebastien.strebelle@vinci.be",
  "password": "password123"
}

### Read user by id
GET http://localhost:8080/users/1
Authorization: {{token}}

### Update user
PUT http://localhost:8080/users/1
Authorization: {{token}}
Content-Type: application/json

{
  "email": "sebastien.strebelle@vinci.be",
  "firstname": "Katherine",
  "lastname": "mareault",
  "id": 1
}

### Delete user
DELETE http://localhost:8080/users/4
Authorization: {{token}}

### GET TRIPS WHERE USER IS THE DRIVER
GET http://localhost:8080/users/1/driver
Authorization: {{token}}


### Get trips where user is a passenger
GET http://localhost:8080/users/5/passenger
Authorization: {{token}}


### Get notifications by user
GET http://localhost:8080/users/1/notifications
Authorization: {{token}}

### Delete user notif
DELETE http://localhost:8080/users/1/notifications
Authorization: {{token}}

### Create a trip
POST http://localhost:8080/trips
Authorization: {{token}}
Content-Type: application/json

{
  "origin": {
    "latitude": 1.00,
    "longitude": 1.00
  },
  "destination": {
    "latitude": 3.00,
    "longitude": 2.00
  },
  "departure" : "2025-05-01",
  "driver_id": 2,
  "available_seating": 2
}

### Read Optionnal Trip
GET http://localhost:8080/trips?destinationLat=3.00&destinationLong=2.00&departure=2025-05-01
Authorization: {{token}}

### Read All Trips
GET http://localhost:8080/trips
Authorization: {{token}}

### get trip
GET http://localhost:8080/trips/3
Authorization: {{token}}

### delete trip
DELETE http://localhost:8080/trips/2
Authorization: {{token}}

### Get list passenger of a Trip
GET http://localhost:8080/trips/1/passengers
Authorization: {{token}}

### add passenger
POST http://localhost:8080/trips/1/passengers/3
Authorization: {{token}}

### delete passenger
DELETE http://localhost:8080/trips/2/passengers/2
Authorization: {{token}}

### update passenger
PUT http://localhost:8080/trips/1/passengers/3?etat=ACCEPTED
Authorization: {{token}}

### get passenger status
GET http://localhost:8080/trips/1/passengers/1
Authorization: {{token}}